theme: jekyll-theme-minimal
title: GREEN_ADA 
description:  GREEN_ADA Pool is a Eco-Friendly and sustainable staking pool taking part in securing the Cardano block-chain.
logo: https://www.directive.com//images/easyblog_images/13843/greenworld400.jpg
show_downloads: false
github:
 is_user_page: false
 is_project_page: false

// your styles here
 .masthead__menu { 
  color: red;
}
