theme: jekyll-theme-minimal
description:  GREEN_ADA Pool is a Eco-Friendly and Sustainable Staking Pool Dedicated taking part in securing the Cardano block-chain.
# logo credits: https://pixabay.com/en/artificial-neural-network-ann-3501528/
logo: https://www.directive.com//images/easyblog_images/13843/greenworld400.jpg
show_downloads: false
github:
 is_user_page: false
 is_project_page: false

